ENV: dev
PORT: 8080
LOG_LEVEL: debug
REDIS_ENABLED: true
REDIS_HOST: localhost
REDIS_PORT: 6379
DATABASE_HOST: localhost
DATABASE_PORT: 5432
DATABASE_NAME: test
DATABASE_PASSWORD:
DATABASE_USER: postgres